-- 코드를 입력하세요
SELECT DISTINCT OS.USER_ID, OS.PRODUCT_ID
FROM ONLINE_SALE OS
WHERE EXISTS (
    SELECT 1
    FROM ONLINE_SALE OS2
    WHERE OS.USER_ID = OS2.USER_ID
    AND OS.PRODUCT_ID = OS2.PRODUCT_ID
    AND OS.SALES_DATE != OS2.SALES_DATE
)
ORDER BY OS.USER_ID ASC, OS.PRODUCT_ID DESC;