-- 코드를 입력하세요
WITH A AS (
    SELECT WRITER_ID, SUM(PRICE) AS TOTAL_SALES
    FROM USED_GOODS_BOARD
    WHERE STATUS = "DONE"
    GROUP BY WRITER_ID
)
SELECT UGU.USER_ID, UGU.NICKNAME, A.TOTAL_SALES
FROM USED_GOODS_USER UGU
JOIN A ON A.WRITER_ID = UGU.USER_ID
WHERE A.TOTAL_SALES >= 700000
ORDER BY A.TOTAL_SALES;