-- 코드를 입력하세요
WITH A AS(
    SELECT CAR_ID, COUNT(*) AS RENT_COUNT
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE MONTH(START_DATE) BETWEEN "08" AND "10"
    AND YEAR(START_DATE) = "2022"
    GROUP BY CAR_ID
    HAVING RENT_COUNT >= 5
)
SELECT MONTH(T.START_DATE) AS MONTH, T.CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY T
JOIN A ON T.CAR_ID = A.CAR_ID
WHERE MONTH(T.START_DATE) BETWEEN "08" AND "10"
AND YEAR(T.START_DATE) = "2022"
GROUP BY MONTH, T.CAR_ID
HAVING COUNT(HISTORY_ID) > 0
ORDER BY MONTH ASC, T.CAR_ID DESC;