#1
SELECT ugb.TITLE, ugb.BOARD_ID, ugr.REPLY_ID, ugr.WRITER_ID, ugr.CONTENTS, DATE_FORMAT(ugr.CREATED_DATE, '%Y-%m-%d') as CREATED_DATE
FROM USED_GOODS_BOARD ugb
INNER JOIN USED_GOODS_REPLY ugr ON ugr.BOARD_ID = ugb.BOARD_ID
WHERE ugr.CREATED_DATE >= '2022-10-01'
  AND ugr.CREATED_DATE < '2022-11-01'
ORDER BY ugr.CREATED_DATE ASC, ugb.TITLE ASC;


#2
SELECT ugb.TITLE, ugb.BOARD_ID, ugr.REPLY_ID,ugr.WRITER_ID, ugr.CONTENTS, DATE_FORMAT(ugr.CREATED_DATE, '%Y-%m-%d') as CREATED_DATE
from USED_GOODS_BOARD ugb, USED_GOODS_REPLY ugr
where ugr.BOARD_ID = ugb.BOARD_ID
and ugb.CREATED_DATE >= '2022-10-01'
and ugb.CREATED_DATE < '2022-11-01'
order by ugr.CREATED_DATE ASC,
ugb.TITLE ASC
